<a href="https://colab.research.google.com/github/Rohit2303A510J0/23CSBTB28/blob/main/a1_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1 - Implement Basic Data Structures using Numpy, Pandas

In [2]:
import numpy as np

In [ ]:
# Types of list
list_example = [1, "Hello", [1, 2], 4.5, 5, {"name": "Rohit", "age": 18}]
print(list_example)
print(list_example[2])
print(type(list_example))

[1, 'Hello', [1, 2], 4.5, 5, {'name': 'Rohit', 'age': 18}]
[1, 2]
<class 'list'>


In [ ]:
dict_example = {'name': 'Rohit', 'occupation': 'student', 'age': 18}
print(dict_example)
print(type(dict_example))

{'name': 'Rohit', 'occupation': 'student', 'age': 18}
<class 'dict'>


In [ ]:
set_example = {1, 2, 3, 4, 5}
print(set_example)
print(type(set_example))

{1, 2, 3, 4, 5}
<class 'set'>


In [ ]:
tuple_example = (1, 2, 3, 4, 5)
print(tuple_example)
print(type(tuple_example))

(1, 2, 3, 4, 5)
<class 'tuple'>


In [ ]:
string_example = "Hello World!"
print(string_example)
print(type(string_example))

Hello World!
<class 'str'>


In [4]:
# Creating an array
arr = np.array([50, 20, 40, 30, 10])

print(arr)
print(arr[0])
print(arr[:2])
print(type(arr))

[50 20 40 30 10]
50
[50 20]
<class 'numpy.ndarray'>


In [5]:
print(arr.ndim) # To get no. of dimensions of an array
print(arr.shape) # Gets shape of array
print(arr.size) # Gets total number of elements
print(arr.dtype) # Gets the data type of elements stored in array
print(np.sort(arr)) # Sorts the array
result = np.concatenate((arr, np.array([60, 70, 80])))
print(result.reshape(4, 2)) # Reshaping the array

1
(5,)
5
int64
[10 20 30 40 50]
[[50 20]
 [40 30]
 [10 60]
 [70 80]]


In [6]:
print(result.shape)
# Converting into row or column vector
dim = result[:, np.newaxis]
print(dim)

# Expanding dimensions at an index
b = np.expand_dims(result, axis=0)
print(b)

(8,)
[[50]
 [20]
 [40]
 [30]
 [10]
 [60]
 [70]
 [80]]
[[50 20 40 30 10 60 70 80]]


In [7]:
# Slicing and indexing
data = np.array([[1, 2, 3], [2, 3, 4], [4, 3, 2]])
print(data[0:2])
print(data[2, 0:1])

[[1 2 3]
 [2 3 4]]
[4]


In [ ]:
# Basic operations
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(a.sum())
print(a * 2) # Broadcasting

implement logaritmic and exponential functions

In [ ]:
print(np.sin(np.pi / 2))
print(np.log(np.e))
print(np.log2(2))
print(np.exp(0))