<a href="https://colab.research.google.com/github/Rohit2303A510J0/23CSBTB28/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creation of Array and Array operation

In [1]:
import numpy as np

In [23]:
# Creating an array
arr = np.array([50, 20, 40, 30, 10])

print(arr)
print(arr[0])
print(arr[:2])
print(type(arr))

[50 20 40 30 10]
50
[50 20]
<class 'numpy.ndarray'>


In [36]:
print(arr.ndim) # To get no. of dimensions of an array
print(arr.shape) # Gets shape of array
print(arr.size) # Gets total number of elements
print(arr.dtype) # Gets the data type of elements stored in array
print(np.sort(arr)) # Sorts the array
result = np.concatenate((arr, np.array([60, 70, 80])))
print(result.reshape(4, 2)) # Reshaping the array

1
(5,)
5
int64
[10 20 30 40 50]
[[50 20]
 [40 30]
 [10 60]
 [70 80]]


In [32]:
print(result.shape)
# Converting into row or column vector
dim = result[:, np.newaxis]
print(dim)

# Expanding dimensions at an index
b = np.expand_dims(result, axis=0)
print(b)

(8,)
[[50]
 [20]
 [40]
 [30]
 [10]
 [60]
 [70]
 [80]]
[[50 20 40 30 10 60 70 80]]


In [41]:
# Slicing and indexing
data = np.array([[1, 2, 3], [2, 3, 4], [4, 3, 2]])
print(data[0:2])
print(data[2, 0:1])

[[1 2 3]
 [2 3 4]]
[4]


In [43]:
# Basic operations
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(a.sum())
print(a * 2) # Broadcasting

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[0.5        0.66666667 0.75      ]
6
[2 4 6]
